services:
  - type: web
    name: cdm-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://cdm-backend.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
